upstream {{ cookiecutter.project }} {
    # 服务名称:端口，要与docker-compose.prd.yaml中配置一致
    server {{ cookiecutter.project }}:8000;  
    keepalive 32;
}

server {
    listen 80;
    # 一定要添加生产环境的域名！
    server_name localhost server.example.com;

    # 最大上传50M
    client_max_body_size 50M;

    # 静态
    location ^~ /static/ {
        # 路径要和 docker-compose.yaml 中的 volume 对应
        alias /var/www/static/;
        expires 10d;
        add_header Cache-Control "public, max-age=864000, immutable";
        access_log off;
    }

    # 媒体
    location ^~ /media/ {
        # 路径要和 docker-compose.yaml 中的 volume 对应
        alias /var/www/media/;
        expires 10d;
        add_header Cache-Control "public, max-age=864000";
    }

    location / {
        # 注意这里的名称要和上面的 upstream 名称对应，尾部加斜杠去掉 URI 前缀，不加则保留
        proxy_pass         http://{{ cookiecutter.project }};
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-Forwarded-Port $server_port;
    }

    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    add_header X-XSS-Protection "1; mode=block" always;
}