upstream site1_backend {
    server site1:8000;  # 容器名称:端口（来自 site1 的 compose）
    keepalive 32;
}

server {
    listen 80;
    server_name site1.example.com;

    # 最大上传50M
    client_max_body_size 50M;

    # 静态
    location ^~ /static/ {
        # 路径要和 docker-compose.yaml 中的 volume 对应
        alias /sites/site1/static/;
        expires 10d;
        add_header Cache-Control "public, max-age=864000, immutable";
        access_log off;
    }

    # 媒体
    location ^~ /media/ {
        # 路径要和 docker-compose.yaml 中的 volume 对应
        alias /sites/site1/media/;
        expires 10d;
        add_header Cache-Control "public, max-age=864000";
    }

    location / {
        # 注意这里的名称要和上面的 upstream 名称对应，尾部要加斜杠去掉 URI 前缀
        proxy_pass         http://site1_backend/;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 60s;
    }

    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    add_header X-XSS-Protection "1; mode=block" always;
}