"""
Django settings for {{ cookiecutter.project }} project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ
{% if cookiecutter.use_sentry -%}
import sentry_sdk
{%- endif %}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(DEBUG=(bool, True))

# take environment variables from .env file
environ.Env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
DEBUG = env('DEBUG')
SECRET_KEY = env('SECRET_KEY')
FORCE_SCRIPT_NAME = env.str('FORCE_SCRIPT_NAME') if env.str('FORCE_SCRIPT_NAME') else None

# Hosts/domain names that are valid for this site
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS') if env.list('ALLOWED_HOSTS') else []

# CSRF trusted origins
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS') if env.list('CSRF_TRUSTED_ORIGINS') else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    {% if cookiecutter.use_celery -%}
    'django_celery_beat',
    {%- endif %}
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '{{ cookiecutter.project }}.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '{{ cookiecutter.project }}.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
        'CONN_MAX_AGE': env.int('DB_CONN_MAX_AGE'),
    }
}

{% if cookiecutter.use_redis -%}
# cache setting
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"redis://{env('REDIS_HOST')}:{env('REDIS_PORT')}",
    }
}
{%- endif %}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = '{{ cookiecutter.language }}'

TIME_ZONE = '{{ cookiecutter.timezone }}'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

if FORCE_SCRIPT_NAME:
    STATIC_URL = FORCE_SCRIPT_NAME + '/static/'  # type: ignore
else:
    STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'

if FORCE_SCRIPT_NAME:
    MEDIA_URL = FORCE_SCRIPT_NAME + '/media/'  # type: ignore
else:
    MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

{% if cookiecutter.use_celery -%}
# Celery 配置
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default=f"redis://{env('REDIS_HOST')}:{env('REDIS_PORT')}/1")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default=f"redis://{env('REDIS_HOST')}:{env('REDIS_PORT')}/2")
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'

# Celery Beat 使用数据库调度器
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
{%- endif %}

{% if cookiecutter.use_sentry -%}
# sentry 配置
SENTRY_DSN = env("SENTRY_DSN", default="")
if SENTRY_DSN:

    sentry_params = {"dsn": SENTRY_DSN, "send_default_pii": True}

    # 是否启用日志集成
    if env('SENTRY_LOG', bool, default=False):
        sentry_params["enable_logs"] = True
    # 采样率，范围是0.0到1.0，或者-1.0表示禁用
    if env('SENTRY_TRACES_SAMPLE_RATE', float, default=-1.0) >= 0:
        sentry_params["traces_sample_rate"] = env('SENTRY_TRACES_SAMPLE_RATE', float)
    # 性能分析，trace或cpu
    if env('SENTRY_PROFILE', str, default="") in ("trace", "cpu"):
        sentry_params["profile_lifecycle"] = env('SENTRY_PROFILE', str)

    sentry_sdk.init(**sentry_params)
{%- endif %}

# 日志设置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'request_id': {},
    },
    'formatters': {
        'verbose': {'format': '[%(asctime)s] %(levelname)s %(name)s %(message)s'},
        'simple': {'format': '%(levelname)s %(message)s'},
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'filters': [],
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filters': [],
            'formatter': 'verbose',
            'filename': BASE_DIR / env("LOGFILE", str, default='logs/{{ cookiecutter.project }}.log'),
            'encoding': 'utf-8',
            'when': 'midnight',  # 每天切割
            'interval': 1,
            'backupCount': 10,  # 保留10天的日志
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
